# Generated by Django 6.0.3 on 2026-03-19 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0005_interactionlog_asked_by"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chatsession",
            options={"ordering": ["-updated_at"]},
        ),
        migrations.AlterModelOptions(
            name="interactionlog",
            options={"ordering": ["created_at"]},
        ),
        migrations.AlterField(
            model_name="interactionlog",
            name="asked_by_display_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="interactionlog",
            name="asked_by_email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AlterField(
            model_name="interactionlog",
            name="asked_by_user_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="interactionlog",
            name="ticket_raised",
            field=models.BooleanField(default=False),
        ),
    ]
