# Generated by Django 6.0.3 on 2026-03-20 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_alter_chatsession_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactionlog',
            name='ticket_comment',
            field=models.TextField(blank=True, default=''),
        ),
    ]
