# Generated by Django 6.0.3 on 2026-03-20 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0007_interactionlog_ticket_comment"),
        ("chatbot", "0007_platformrole_userprofile_platform_role"),
    ]

    operations = []
